package com.wand.app.data

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class TaskBoardModelsTest {
    @Test
    fun boardTaskParserReadsWorkspaceAgentAndSessions() {
        val task = BoardTask.parse(
            JSONObject()
                .put("id", "task-1")
                .put("workspaceId", "ws-1")
                .put("identifier", "TASK-1")
                .put("title", "修顶栏")
                .put("description", "对齐 iOS")
                .put("status", "doing")
                .put("priority", "high")
                .put("labels", JSONArray().put("ui"))
                .put("sortOrder", 2)
                .put(
                    "agent",
                    JSONObject()
                        .put("provider", "codex")
                        .put("model", "default")
                        .put("thinkingEffort", "deep"),
                )
                .put("sessionIds", JSONArray().put("sess-1"))
                .put(
                    "sessions",
                    JSONArray().put(
                        JSONObject()
                            .put("id", "sess-1")
                            .put("provider", "codex")
                            .put("sessionKind", "structured")
                            .put("title", "修顶栏")
                            .put("status", "running")
                            .put("cwd", "/repo")
                            .put("model", "gpt-5")
                            .put("thinkingEffort", "deep"),
                    ),
                )
                .put(
                    "workspace",
                    JSONObject().put("id", "ws-1").put("name", "wand").put("cwd", "/repo"),
                ),
        )

        requireNotNull(task)
        assertEquals("task-1", task.id)
        assertEquals("ws-1", task.workspaceId)
        assertEquals("TASK-1", task.identifier)
        assertEquals("doing", task.status)
        assertEquals("high", task.priority)
        assertEquals(listOf("ui"), task.labels)
        assertEquals("codex", task.agent?.provider)
        assertEquals("wand", task.workspace?.name)
        assertEquals(listOf("sess-1"), task.sessionIds)
        assertEquals("sess-1", task.sessions.single().id)
        assertTrue(task.sessions.single().isStructured)
    }

    @Test
    fun boardTaskParserAllowsUnassignedProjectAndAgent() {
        val task = BoardTask.parse(JSONObject().put("id", "task-2").put("title", "草稿"))
        requireNotNull(task)
        assertNull(task.workspaceId)
        assertNull(task.agent)
        assertEquals("todo", task.status)
        assertEquals("none", task.priority)
        assertTrue(task.sessions.isEmpty())
        // 老服务端不返回 titleSource，客户端按用户手写处理。
        assertEquals("user", task.titleSource)
    }

    @Test
    fun boardTaskParserReadsAutoGeneratedTitleSource() {
        val task = BoardTask.parse(
            JSONObject().put("id", "task-3").put("title", "按描述生成的标题").put("titleSource", "auto"),
        )
        requireNotNull(task)
        assertEquals("auto", task.titleSource)
    }

    @Test
    fun createBodyOmitsWorkspaceAsJsonNull() {
        val unassigned = createBoardTaskBody("标题", "说明", "todo", "none", null)
        assertTrue(unassigned.isNull("workspaceId"))
        val assigned = createBoardTaskBody("标题", "", "doing", "high", "ws-1")
        assertEquals("ws-1", assigned.getString("workspaceId"))
        assertEquals("doing", assigned.getString("status"))
        val withAgent = createBoardTaskBody(
            "标题",
            "说明",
            "todo",
            "none",
            null,
            BoardTaskAgent("pi", "default", "off"),
        )
        assertEquals("pi", withAgent.getJSONObject("agent").getString("provider"))
    }

    @Test
    fun patchBodyOnlyWritesProvidedFields() {
        val patch = patchBoardTaskBody(status = "done", workspaceId = null)
        assertEquals("done", patch.getString("status"))
        assertTrue(patch.isNull("workspaceId"))
        assertFalse(patch.has("title"))
        assertFalse(patch.has("agent"))
    }

    @Test
    fun statusAndPriorityLabelsCoverBoardColumns() {
        assertEquals("待办", boardTaskStatusLabel("todo"))
        assertEquals("进行中", boardTaskStatusLabel("doing"))
        assertEquals("已完成", boardTaskStatusLabel("done"))
        assertEquals("紧急", boardTaskPriorityLabel("urgent"))
        assertEquals("无优先级", boardTaskPriorityLabel("none"))
        assertEquals("Pi", boardTaskProviderLabel("pi"))
    }

    @Test
    fun sessionsGroupByTheAgentsThatRan() {
        val claude = BoardTaskAgent("claude", "opus", "deep")
        val groups = groupBoardSessionsByAgent(
            listOf(
                BoardTaskSession("s1", "claude", "structured", "修登录", "running", "/repo", "opus", "deep"),
                BoardTaskSession("s2", "claude", "structured", "补测试", "exited", "/repo", "sonnet", "off"),
                BoardTaskSession("s3", "codex", "structured", "实现 API", "idle", "/repo", "gpt-5", "standard"),
            ),
            claude,
        )
        assertEquals(listOf("claude", "codex"), groups.map { it.provider })
        assertEquals(listOf("s1", "s2"), groups[0].sessions.map { it.id })
        assertEquals(listOf("s3"), groups[1].sessions.map { it.id })
        assertEquals("Claude · Codex", boardTaskAgentLabels(groups.flatMap { it.sessions }, claude))

        val pending = groupBoardSessionsByAgent(emptyList(), BoardTaskAgent("pi", "default", "off"))
        assertEquals(1, pending.size)
        assertEquals("pi", pending[0].provider)
        assertTrue(pending[0].sessions.isEmpty())
    }
}
